---

- name: Deploy Jupiter Website
  hosts: webservers
  become: yes
  become_user: root

  tasks:
    - name: Update EC2 Instance
      yum:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install Apache Server
      yum:
        name: httpd
        state: latest

    - name: Copy the Web Files From S3 Bucket Into the HTML Directory
      command: aws s3 sync s3://jupiter-project-bucket /var/www/html

    - name: Start Apache Server, If Not Started
      service:
        enabled: yes
        name: httpd
        state: started